import { Contact } from "./types";

export const sampleContacts: Contact[] = [
  {
    id: "1",
    name: "Sarah Chen",
    company: "Sequoia Capital",
    role: "Principal",
    topics: ["Venture Capital", "SaaS", "Portfolio Strategy"],
    followUpDate: "2026-03-26",
    keyNote: "Interested in edtech startups. Wants to see traction metrics before Series A. Mentioned the Sequoia Arc program as a potential fit.",
    createdAt: "2026-03-20T14:30:00Z",
  },
  {
    id: "2",
    name: "Marcus Johnson",
    company: "McKinsey & Company",
    role: "Associate",
    topics: ["Strategy", "MBA Recruiting", "Operations"],
    followUpDate: "2026-04-02",
    keyNote: "Recruits for the Chicago office. Loves candidates with prior startup experience. Follow up with resume and cover letter.",
    createdAt: "2026-03-19T10:00:00Z",
  },
  {
    id: "3",
    name: "Priya Nair",
    company: "Google",
    role: "Product Manager",
    topics: ["Product Management", "AI/ML", "Growth"],
    followUpDate: "2026-03-22",
    keyNote: "Working on Google's AI integrations in Workspace. Suggested reaching out to her PM lead. Was very warm and open to referrals.",
    createdAt: "2026-03-18T16:45:00Z",
  },
  {
    id: "4",
    name: "James Whitfield",
    company: "Goldman Sachs",
    role: "VP, Investment Banking",
    topics: ["Investment Banking", "M&A", "Tech Sector"],
    followUpDate: "2026-04-10",
    keyNote: "Covers tech M&A. Said the best time to apply is September. Recommended connecting with two analysts on his team.",
    createdAt: "2026-03-17T09:15:00Z",
  },
  {
    id: "5",
    name: "Anika Osei",
    company: "Andreessen Horowitz",
    role: "Deal Team",
    topics: ["VC", "Consumer Tech", "Crypto"],
    followUpDate: "2026-04-15",
    keyNote: "Focused on consumer and crypto investments. Very interested in MBA interns for summer. Send LinkedIn note this week.",
    createdAt: "2026-03-16T11:00:00Z",
  },
  {
    id: "6",
    name: "Liam Torres",
    company: "Stripe",
    role: "Engineering Manager",
    topics: ["Fintech", "Engineering Leadership", "Payments"],
    followUpDate: "2026-04-20",
    keyNote: "Building out the SMB payments team. Looking for PMs with technical background. Great culture, hybrid in SF.",
    createdAt: "2026-03-15T14:00:00Z",
  },
];
